# ----------- CONFIGURABLE START -----------
title:            "Khairul Slt"
description:      "Such theme, very cool."
url:              https://khairulslt.github.io # Site url, without a slash at the end.
signoff:          "khairulslt" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-164634484-1
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         About me
    url:          /about
    external:     false
  - name:         Projects
    url:          /projects
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
plugins:
  - jemoji